### ISSUE TITLE
Problems encountered when running gmtracker_app.py and motchanllenge_tracking.py

### ISSUE THREAD

**Issue by 1359347500cwc** [jiaweihe1996/GMTracker#12]
I have finished 1~4 steps in 'Getting Started'. However, when I try to run the first example code in step 5:

python gmtracker_app.py --sequence_dir data/MOT17/test/MOT17-01 --detection_file npy/npytest_tracktor/MOT17-01-DPM.npy --checkpoint_dir experiments/static/params/0001 --max_age 100 --reid_thr 0.6 --output_file results/test/MOT17-01-DPM.txt

An error occors:
torch.Size([2171, 512])
Loading model parameters from experiments/static/params/0001/params.pt
torch.Size([2171, 512])
Processing MOT17-01 frame 00001
Nothing to match at this level
Processing MOT17-01 frame 00002
Nothing to match at this level
Processing MOT17-01 frame 00003
error parsing inputs
Traceback (most recent call last):
  File "gmtracker_app.py", line 286, in <module>
    args.max_age, args.n_init, args.reid_thr, args.checkpoint_dir)
  File "gmtracker_app.py", line 240, in run
    frame_callback(frame_idx)
  File "gmtracker_app.py", line 227, in frame_callback
    tracker.update(detections, seq_info["sequence_name"], frame_idx, checkpoint_dir)
  File "/home/cwc/GMTracker/utils/tracker.py", line 119, in update
    self._match(detections,video,frame,checkpoint_dir)
  File "/home/cwc/GMTracker/utils/tracker.py", line 149, in _match
    self.max_age, self.tracks, detections, confirmed_tracks,reid_thr=self.reid_thr,seq_name=video,ckp_dir=checkpoint_dir)
  File "/home/cwc/GMTracker/GMMOT/assignment.py", line 155, in graph_matching
    track_indices_l, unmatched_detections,reid_thr,seq_name,ckp_dir)
  File "/home/cwc/GMTracker/GMMOT/assignment.py", line 107, in quadratic_matching
    indices, thr_flag = graphnet.forward(data1, data2, kf_gate, reid_thr, iou, start_src, end_src, start_tgt, end_tgt, seq_name, inverse_flag=False)
  File "/home/cwc/GMTracker/GMMOT/gmatching.py", line 107, in forward
    prob.solve(solver=cp.SCS, gpu=True, use_indirect=True)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 436, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 928, in _solve
    self, data, warm_start, verbose, kwargs)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 341, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 308, in solve_via_data
    results = scs.solve(args, cones, verbose=verbose, **solver_opts)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/scs-3.0.0-py3.6-linux-x86_64.egg/scs/__init__.py", line 104, in solve
    Pcolptr, b, c, cone, warm, **kwargs)
TypeError: 'eps' is an invalid keyword argument for this function

the Same error in  python motchanllenge_tracking.py:

torch.Size([2171, 512])
Loading model parameters from experiments/static/params/0001/params.pt
torch.Size([2171, 512])
Processing MOT17-01 frame 00001
Nothing to match at this level
Processing MOT17-01 frame 00002
Nothing to match at this level
Processing MOT17-01 frame 00003
error parsing inputs
Traceback (most recent call last):
  File "gmtracker_app.py", line 286, in <module>
    args.max_age, args.n_init, args.reid_thr, args.checkpoint_dir)
  File "gmtracker_app.py", line 240, in run
    frame_callback(frame_idx)
  File "gmtracker_app.py", line 227, in frame_callback
    tracker.update(detections, seq_info["sequence_name"], frame_idx, checkpoint_dir)
  File "/home/cwc/GMTracker/utils/tracker.py", line 119, in update
    self._match(detections,video,frame,checkpoint_dir)
  File "/home/cwc/GMTracker/utils/tracker.py", line 149, in _match
    self.max_age, self.tracks, detections, confirmed_tracks,reid_thr=self.reid_thr,seq_name=video,ckp_dir=checkpoint_dir)
  File "/home/cwc/GMTracker/GMMOT/assignment.py", line 155, in graph_matching
    track_indices_l, unmatched_detections,reid_thr,seq_name,ckp_dir)
  File "/home/cwc/GMTracker/GMMOT/assignment.py", line 107, in quadratic_matching
    indices, thr_flag = graphnet.forward(data1, data2, kf_gate, reid_thr, iou, start_src, end_src, start_tgt, end_tgt, seq_name, inverse_flag=False)
  File "/home/cwc/GMTracker/GMMOT/gmatching.py", line 107, in forward
    prob.solve(solver=cp.SCS, gpu=True, use_indirect=True)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 436, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 928, in _solve
    self, data, warm_start, verbose, kwargs)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 341, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 308, in solve_via_data
    results = scs.solve(args, cones, verbose=verbose, **solver_opts)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/scs-3.0.0-py3.6-linux-x86_64.egg/scs/__init__.py", line 104, in solve
    Pcolptr, b, c, cone, warm, **kwargs)
TypeError: 'eps' is an invalid keyword argument for this function
['python', 'gmtracker_app.py', '--sequence_dir=data/MOT17/test/MOT17-01', '--detection_file=npy/npytest_tracktor/MOT17-01-FRCNN.npy', '--checkpoint_dir=experiments/static/params/0001/', '--max_age=100', '--reid_thr=0.6', '--output_file=result/final/MOT17-01-FRCNN.txt']
torch.Size([3106, 512])
Loading model parameters from experiments/static/params/0001/params.pt
torch.Size([3106, 512])
Processing MOT17-01 frame 00001
Nothing to match at this level
Processing MOT17-01 frame 00002
Nothing to match at this level
Processing MOT17-01 frame 00003
error parsing inputs
Traceback (most recent call last):
  File "gmtracker_app.py", line 286, in <module>
    args.max_age, args.n_init, args.reid_thr, args.checkpoint_dir)
  File "gmtracker_app.py", line 240, in run
    frame_callback(frame_idx)
  File "gmtracker_app.py", line 227, in frame_callback
    tracker.update(detections, seq_info["sequence_name"], frame_idx, checkpoint_dir)
  File "/home/cwc/GMTracker/utils/tracker.py", line 119, in update
    self._match(detections,video,frame,checkpoint_dir)
  File "/home/cwc/GMTracker/utils/tracker.py", line 149, in _match
    self.max_age, self.tracks, detections, confirmed_tracks,reid_thr=self.reid_thr,seq_name=video,ckp_dir=checkpoint_dir)
  File "/home/cwc/GMTracker/GMMOT/assignment.py", line 155, in graph_matching
    track_indices_l, unmatched_detections,reid_thr,seq_name,ckp_dir)
  File "/home/cwc/GMTracker/GMMOT/assignment.py", line 109, in quadratic_matching
    indices, thr_flag = graphnet.forward(data2, data1, kf_gate.T, reid_thr, iou.t(), start_tgt, end_tgt, start_src, end_src, seq_name, inverse_flag=True)
  File "/home/cwc/GMTracker/GMMOT/gmatching.py", line 91, in forward
    prob.solve(solver=cp.SCS, gpu=True, use_indirect=True)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 436, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 928, in _solve
    self, data, warm_start, verbose, kwargs)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 341, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 308, in solve_via_data
    results = scs.solve(args, cones, verbose=verbose, **solver_opts)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/scs-3.0.0-py3.6-linux-x86_64.egg/scs/__init__.py", line 104, in solve
    Pcolptr, b, c, cone, warm, **kwargs)
TypeError: 'eps' is an invalid keyword argument for this function
['python', 'gmtracker_app.py', '--sequence_dir=data/MOT17/test/MOT17-01', '--detection_file=npy/npytest_tracktor/MOT17-01-SDP.npy', '--checkpoint_dir=experiments/static/params/0001/', '--max_age=100', '--reid_thr=0.6', '--output_file=result/final/MOT17-01-SDP.txt']
torch.Size([3222, 512])
Loading model parameters from experiments/static/params/0001/params.pt
torch.Size([3222, 512])
Processing MOT17-01 frame 00001
Nothing to match at this level
Processing MOT17-01 frame 00002
Nothing to match at this level
Processing MOT17-01 frame 00003
error parsing inputs
Traceback (most recent call last):
  File "gmtracker_app.py", line 286, in <module>
    args.max_age, args.n_init, args.reid_thr, args.checkpoint_dir)
  File "gmtracker_app.py", line 240, in run
    frame_callback(frame_idx)
  File "gmtracker_app.py", line 227, in frame_callback
    tracker.update(detections, seq_info["sequence_name"], frame_idx, checkpoint_dir)
  File "/home/cwc/GMTracker/utils/tracker.py", line 119, in update
    self._match(detections,video,frame,checkpoint_dir)
  File "/home/cwc/GMTracker/utils/tracker.py", line 149, in _match
    self.max_age, self.tracks, detections, confirmed_tracks,reid_thr=self.reid_thr,seq_name=video,ckp_dir=checkpoint_dir)
  File "/home/cwc/GMTracker/GMMOT/assignment.py", line 155, in graph_matching
    track_indices_l, unmatched_detections,reid_thr,seq_name,ckp_dir)
  File "/home/cwc/GMTracker/GMMOT/assignment.py", line 107, in quadratic_matching
    indices, thr_flag = graphnet.forward(data1, data2, kf_gate, reid_thr, iou, start_src, end_src, start_tgt, end_tgt, seq_name, inverse_flag=False)
  File "/home/cwc/GMTracker/GMMOT/gmatching.py", line 91, in forward
    prob.solve(solver=cp.SCS, gpu=True, use_indirect=True)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 436, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 928, in _solve
    self, data, warm_start, verbose, kwargs)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 341, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 308, in solve_via_data
    results = scs.solve(args, cones, verbose=verbose, **solver_opts)
  File "/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/scs-3.0.0-py3.6-linux-x86_64.egg/scs/__init__.py", line 104, in solve
    Pcolptr, b, c, cone, warm, **kwargs)
TypeError: 'eps' is an invalid keyword argument for this function
22it [00:04,  5.36it/s]

**Comment by jiaweihe1996** [comment]
`scs-python` 3.0.0 is not supported by `cvxpy` library now. Please downgrade `scs-python`.

**Comment by 1359347500cwc** [comment]
Thank you for your reply!   **So which version is available for cvxpy now?**
**I have tried the scs-2.1.4  but when i use python setup.py --scs --gpu 
it give me an error about "fatal error: scs_matrix.h: No such file or directory"**

Here is the  complete Track：
Namespace(blas64=False, extraverbose=False, float32=False, gpu=True, gpu_atrans=True, int32=False, scs=True)
running install
running bdist_egg
running egg_info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/home/cwc/anaconda3/envs/GMTracker/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/usr/include', '/home/cwc/anaconda3/envs/GMTracker/include']}
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/home/cwc/anaconda3/envs/GMTracker/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/usr/include', '/home/cwc/anaconda3/envs/GMTracker/include']}
In file included from /home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/scsmodule.c:5:
/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
**src/scsmodule.c:7:10: fatal error: scs_matrix.h: No such file or directory
 #include "scs_matrix.h"
          ^~~~~~~~~~~~~~**
compilation terminated.
error: Command "gcc -pthread -B /home/cwc/anaconda3/envs/GMTracker/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPYTHON -DCTRLC=1 -DCOPYAMATRIX -DUSE_LAPACK -DSCIPY_MKL_H -DHAVE_CBLAS -DSCIPY_MKL_H -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -I/home/cwc/anaconda3/envs/GMTracker/lib/python3.6/site-packages/numpy/core/include -I/usr/local/include -I/usr/include -I/home/cwc/anaconda3/envs/GMTracker/include -I/usr/local/include -I/usr/include -I/home/cwc/anaconda3/envs/GMTracker/include -I/home/cwc/anaconda3/envs/GMTracker/include/python3.6m -c src/scsmodule.c -o build/temp.linux-x86_64-3.6/src/scsmodule.o -O3" failed with exit status 1

I would be grateful if you can help me!!

**Comment by jiaweihe1996** [comment]
Commit `4e4aa0b5d31122dbd6cd405f4401ba353315f92e` from `https://github.com/bodono/scs-python` has been tested by me and can work well.
