### ISSUE TITLE
TypeError: 'eps' is an invalid keyword argument for this function ( running trainGMMOT.py )

### ISSUE THREAD

**Issue by EstellalovesElk** [jiaweihe1996/GMTracker#14]
运行trainGMMOT.py报错：TypeError: 'eps' is an invalid keyword argument for this function

之前安装scs-python gpu时一直报错，联系了scs-python的contributor，作者建议我用最新版本cuda并且安装最新版本的scs-python，因为cuda toolkit中相关api改名了，因此scs-python也有相应修改，我现在运行的环境是cuda11.0，scs-python的版本时3.0.0，运行trainGMMOT.py的这个报错是否与scs-python版本有关？

但是当前scs-python已经更新到最新版本（3.0.0版本），如果这个报错与scs-python版本有关，那么应该使用scs-python的哪个版本呢？

```
error parsing inputs
Traceback (most recent call last):
  File "trainGMMOT.py", line 175, in <module>
    model = train_model(
  File "trainGMMOT.py", line 92, in train_model
    s_pred = model(graph_tracks, graph_dets,iou)
  File "/root/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/workspace/code/GMTracker-main/GMMOT/model.py", line 194, in forward
    s = qp(M,-Mpp,GG,hh,b,bb)
  File "/root/workspace/code/GMTracker-main/qpth/qpth/qp.py", line 107, in forward
    vals[i], zhati, nui, lami, si = solvers.cvxpy.forward_single_np(
  File "/root/workspace/code/GMTracker-main/qpth/qpth/solvers/cvxpy.py", line 20, in forward_single_np
    prob.solve(solver=cp.SCS, gpu=True, use_indirect=True)  # solver=cp.SCS, max_iters=5000, verbose=False)
  File "/root/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 436, in solve
    return solve_func(self, *args, **kwargs)
  File "/root/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 927, in _solve
    solution = solving_chain.solve_via_data(
  File "/root/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 340, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,
  File "/root/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 308, in solve_via_data
    results = scs.solve(args, cones, verbose=verbose, **solver_opts)
  File "/root/.pyenv/versions/3.8.6/lib/python3.8/site-packages/scs-3.0.0-py3.8-linux-x86_64.egg/scs/__init__.py", line 103, in solve
    return _scs_gpu.csolve((m, n), Adata, Aindices, Acolptr, Pdata, Pindices,
TypeError: 'eps' is an invalid keyword argument for this function
```

**Comment by jiaweihe1996** [comment]
Refer to #12.
